<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '479e0d4480f9edc48dff45aa47e6e531',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'postgresql://postgres:yass@localhost:5432/symfony?serverVersion=13&charset=utf8',
  'MAILER_DSN' => 'gmail://densetsu.code@gmail.com:Yass1503.@default',
);
