<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6J73KS6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6J73KS6/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container6J73KS6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container6J73KS6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container6J73KS6\App_KernelProdContainer([
    'container.build_hash' => '6J73KS6',
    'container.build_id' => 'f795ab80',
    'container.build_time' => 1667826924,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6J73KS6');
