<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], [], []],
    'acceuil' => [[], ['_controller' => 'App\\Controller\\AcceuilController::index'], [], [['text', '/acceuil']], [], [], []],
    'app_bloc_competence' => [[], ['_controller' => 'App\\Controller\\BlocCompetenceController::index'], [], [['text', '/bloc/competence']], [], [], []],
    'bts_sio' => [[], ['_controller' => 'App\\Controller\\BtsSioController::index'], [], [['text', '/bts/sio']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'app_contrat' => [[], ['_controller' => 'App\\Controller\\ContratController::index'], [], [['text', '/contrat']], [], [], []],
    'cv' => [[], ['_controller' => 'App\\Controller\\CvController::index'], [], [['text', '/cv']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'ppe' => [[], ['_controller' => 'App\\Controller\\PPEController::index'], [], [['text', '/p/p/e']], [], [], []],
    'stages' => [[], ['_controller' => 'App\\Controller\\StagesController::index'], [], [['text', '/stages']], [], [], []],
    'veille_technologique' => [[], ['_controller' => 'App\\Controller\\VeilleTechnoController::index'], [], [['text', '/veille/techno']], [], [], []],
];
