<?php

namespace Container6J73KS6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlocCompetenceControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BlocCompetenceController' shared autowired service.
     *
     * @return \App\Controller\BlocCompetenceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BlocCompetenceController'] = $instance = new \App\Controller\BlocCompetenceController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\BlocCompetenceController', $container));

        return $instance;
    }
}
