<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6iGzVxw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6iGzVxw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6iGzVxw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6iGzVxw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6iGzVxw\App_KernelDevDebugContainer([
    'container.build_hash' => '6iGzVxw',
    'container.build_id' => '4be7517c',
    'container.build_time' => 1667899910,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6iGzVxw');
