<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_array-iteration_js-node_modules_core-js_internals_dom--711a0d.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-swup_dist_-e1ee25.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-swup_dist_-e1ee25.css',
                '/build/app.css',
            ],
        ],
        'cv' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_array-iteration_js-node_modules_core-js_internals_dom--711a0d.js',
                '/build/cv.js',
            ],
        ],
        'home' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/home.css',
            ],
        ],
        'portfolio' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/portfolio.css',
            ],
        ],
    ],
],

]];
